<?php
/*
 * Developed with the power of phalcon php 2.0
 * Author: Evan Grob
 * Date: May 8, 2016
 */
?>
<!-- Developed with the power of phalcon php 2.0
 * Author: Evan Grob
 * Date: May 8, 2016 -->
<!DOCTYPE html>
<html>
	
	<?php
	$getHeader = new HeaderController();
	$getHeader->getHeader();
	
	?>
	<body>
<div id="wrapper">
<div id="header">
<div id="headerbanner"><a href="http://localhost/allwines/"><img src="http://localhost/allwines/images/banner1.png" width="1200" height="125" /></a></div>
<?php
$menu = new MenuController();
$menu->getMenu();
?>


<div id="main">
<div id="content">

	<p>Welcome to all-wines.com</p>

<img src="<?php echo IMAGES_DIR ?>/allwines.jpg">

<p style="text-align: left;margin-left:50px;margin-right:50px;">This site is designed to be an introduction to wines.  Wines can be categorized by the grapes varietals, growing regions, and pairings with food.  Tastings are an important part of sampling wines and knowing what to keep in mind will make the selection of wine interesting.</p>

</div>
</div>
<div id="sidebar">
	
<h2 >Additional Information</h2>


 
</div>
<?php
	$getFooter = new FooterController();
	$getFooter->getFooter();
	
	?>
</div>
</body>

	
	
</html>